# -*- coding: utf-8 -*-
"""camera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zz6UDyCHNjzyvM9kGTVabAivz5IuQ3pW
"""

# camera.py

import cv2
from config import CAMERA_INDEX, FRAME_WIDTH, FRAME_HEIGHT, BUFFER_SIZE


def setup_camera():
    cap = cv2.VideoCapture(CAMERA_INDEX)

    cap.set(cv2.CAP_PROP_FRAME_WIDTH, FRAME_WIDTH)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, FRAME_HEIGHT)
    cap.set(cv2.CAP_PROP_BUFFERSIZE, BUFFER_SIZE)

    return cap


def release_camera(cap):
    cap.release()
    cv2.destroyAllWindows()