# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_UcZiZSIN3iVYfm9msaXEdvEE5bGsh1
"""

# config.py

MODEL_PATH = "yolo26n.pt"

CAMERA_INDEX = 0
FRAME_WIDTH = 320
FRAME_HEIGHT = 240
BUFFER_SIZE = 1

IMG_SIZE = 320
CONFIDENCE_THRESHOLD = 0.5

WINDOW_NAME = "Obstacle Detection"
WINDOW_WIDTH = 360
WINDOW_HEIGHT = 300