# -*- coding: utf-8 -*-
"""detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CG2N6a0-vAGb4j6L3aHZLCRGGgRgxKF4
"""

# detector.py

from ultralytics import YOLO
from config import MODEL_PATH, IMG_SIZE, CONFIDENCE_THRESHOLD


class ObjectDetector:
    def __init__(self):
        self.model = YOLO(MODEL_PATH)

    def detect(self, frame):
        results = self.model(
            frame,
            imgsz=IMG_SIZE,
            conf=CONFIDENCE_THRESHOLD,
            verbose=False
        )

        detections = []

        for r in results:
            for box in r.boxes:
                cls_id = int(box.cls[0])
                conf = float(box.conf[0])

                x1, y1, x2, y2 = box.xyxy[0].tolist()
                x1, y1, x2, y2 = map(int, [x1, y1, x2, y2])

                class_name = self.model.names[cls_id]

                cx = int((x1 + x2) / 2)
                cy = int((y1 + y2) / 2)

                detection = {
                    "class_id": cls_id,
                    "class_name": class_name,
                    "confidence": conf,
                    "box": [x1, y1, x2, y2],
                    "center": [cx, cy]
                }

                detections.append(detection)

        return detections