# -*- coding: utf-8 -*-
"""fps_counter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UI0XQmZ9XRDX-gecPrabwp7Xv_lJp3IS
"""

# fps_counter.py

import time


class FPSCounter:
    def __init__(self):
        self.prev_time = time.time()

    def calculate(self):
        current_time = time.time()
        fps = 1 / (current_time - self.prev_time)
        self.prev_time = current_time
        return fps