# -*- coding: utf-8 -*-
"""read_stm32

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evHVHDWyCnkxxmMxF1M0mKBUfzQNrsip
"""

import serial

ser = serial.Serial(
    port="/dev/ttyACM0",
    baudrate=115200,
    timeout=1
)

while True:
    line = ser.readline().decode(errors="ignore").strip()
    if line:
        print("STM32 says:", line)