# -*- coding: utf-8 -*-
"""visualizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1do4g-espSdOznJWiIZ01zdBunzw4ZEzS
"""

# visualizer.py

import cv2
from config import WINDOW_NAME, WINDOW_WIDTH, WINDOW_HEIGHT


def setup_window():
    cv2.namedWindow(WINDOW_NAME, cv2.WINDOW_NORMAL)
    cv2.resizeWindow(WINDOW_NAME, WINDOW_WIDTH, WINDOW_HEIGHT)


def draw_detections(frame, detections):
    for det in detections:
        x1, y1, x2, y2 = det["box"]
        cx, cy = det["center"]

        class_name = det["class_name"]
        conf = det["confidence"]

        # Bounding box
        cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)

        # Class name and confidence
        text = f"{class_name} {conf:.2f}"
        cv2.putText(
            frame,
            text,
            (x1, y1 - 5),
            cv2.FONT_HERSHEY_PLAIN,
            1.5,
            (0, 255, 0),
            2
        )

        # Center point
        cv2.circle(frame, (cx, cy), 4, (0, 0, 255), -1)

    return frame


def draw_fps(frame, fps):
    cv2.putText(
        frame,
        f"FPS: {fps:.1f}",
        (20, 50),
        cv2.FONT_HERSHEY_PLAIN,
        2,
        (0, 255, 255),
        2
    )

    return frame


def show_frame(frame):
    cv2.imshow(WINDOW_NAME, frame)