# -*- coding: utf-8 -*-
"""write_stm32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zvStnGnrvEku_KXFVE0YxFXafcZCNlr
"""

import serial
import time

ser = serial.Serial(
    port="/dev/ttyACM0",
    baudrate=115200,
    timeout=1
)

time.sleep(2)

while True:
    cmd = input("Send command to STM32: ")

    ser.write((cmd + "\n").encode())

    response = ser.readline().decode(errors="ignore").strip()
    if response:
        print("STM32 replied:", response)